name: Compare function
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTS_WITH_FUNC: ${{ startWith('Hello', 'He') }}
          ENDS_WITH_FUNC: ${{ endWith('Hello', 'lo') }}